### PR TITLE
beacon/goclient: fix potential zero fee recipient blocks on CL restart

### LINKED ISSUE #2408: Zero fee recipient after beacon node restart due to missing proposer preparation
We observed a case where the beacon node [proposed](https://beaconcha.in/slot/12154001) a vanilla block with `fee_recipient = 0x0000000000000000000000000000000000000000` due to loss of proposer preparation state:
- `prepare_beacon_proposer` was submitted in **epoch X**
- Beacon node restarted in **epoch X+N**
- A proposer duty occurred in **epoch X+N+M**, which was **within the same epoch** as the restart and the prepare submission
- The block was built **without a fee recipient**

This applies to **vanilla blocks** (non-MEV) - the beacon node constructs the execution payload locally, and if no `fee_recipient` is available, it falls back to `0x000...`.

Per [spec](https://ethereum.github.io/beacon-APIs/#/Validator/prepare_beacon_proposer):

> The information supplied for each validator index will persist through the epoch in which the call is submitted and for a further two epochs after that, **or until the beacon node restarts**.

> Note that there is **no guarantee** that the beacon node will use the supplied fee recipient when creating a block proposal. Validators **should confirm** the recipient before signing.

## Current Behavior

- A periodic task submits `prepare_beacon_proposer` **once per epoch**, at the first slot.
- If the beacon node restarts mid-epoch, proposer duties occurring in the **same epoch** may happen **before the next preparation submission**.
- In this case, the beacon node constructs a block with `fee_recipient = 0x000...`.
- Our validator currently does **not validate** the `fee_recipient` field in proposed blocks.
- We also do **not have a fallback strategy** when a proposed block contains a zero recipient - retrying `prepare_beacon_proposer` after this point may not be effective or valid. This behavior should be researched.

## Action Items

- [ ] `ProposerValueCheckF` (value check for consensus data) - check if the address is the same as the configured one. Can be addressed immediately
- [x] **(Needs research)** Detect beacon node restarts and resubmit `prepare_beacon_proposer` immediately to avoid gaps.
- [x] Validate `fee_recipient` in the proposed block before signing; **log** if it's `0x000...`.
- [x] Research whether re-submitting `prepare_beacon_proposer` at the time of a missing/zero recipient is safe or effective.
- [ ] Investigate validator client behavior (e.g., Prysm, Lighthouse) around restarts and proposer preparation persistence.

## Gaps in Our Current Logic

We do **not** submit preparations for:
  - Validators that **will became active next epoch** on the beacon chain.
  - Validators that were **recently registered** or **reactivated (after liquidation)** on the network.
- We **do** submit preparations for **liquidated** validators, which is unnecessary.

Per spec:

> Requests containing currently inactive or unknown validator indices will be accepted, as they may become active at a later epoch.

### PR DESCRIPTION
**Pull request by nkryuchkov**
Closes #2408 

As per [spec](https://ethereum.github.io/beacon-APIs/#/Validator/prepareBeaconProposer), 

> The information supplied for each validator index will persist through the epoch in which the call is submitted and for a further two epochs after that, or until the beacon node restarts.

So when CL restarts, it loses the fee recipient data it had received from the SSV node while it was up. It may take some time until the SSV node submits the preparations again, causing the submission of a proposal with an empty fee recipient.

The PR checks the block fee recipient of the proposal received from CL, and submits a proposal preparation if it's empty, requesting another block afterwards, which should contain the expected fee recipient.

### CODE REVIEW

**Comment by nkryuchkov** [comment]
@greptileai what can be done to increase the confidence score?

**Comment by nkryuchkov** [comment]
@greptileai do a general review please

File: protocol/v2/ssv/runner/proposer.go [hunk 1]
```diff
@@ -190,6 +192,41 @@ func (r *ProposerRunner) ProcessPreConsensus(ctx context.Context, logger *zap.Lo
 		observability.BeaconBlockIsBlindedAttribute(blockSummary.Blinded),
 	))
 
+	// Check if the block has a fee recipient. If not, submit preparations and try again.
+	if summarizeErr == nil && blockSummary.FeeRecipient == (bellatrix.ExecutionAddress{}) {
+		logger.Warn("fee recipient missing from beacon block, resubmitting proposal preparation")
+
+		feeRecipients := map[phase0.ValidatorIndex]bellatrix.ExecutionAddress{
+			r.GetShare().ValidatorIndex: r.GetShare().FeeRecipientAddress,
+		}
```
Comment (iurii-ssv) [inline protocol/v2/ssv/runner/proposer.go]: Technically it's very likely that accessing `.FeeRecipientAddress` on `r.GetShare()` in not thread-safe thing to do (if it's not triggering race-detector the only reason it doesn't is there is some unintentional/hidden/inexplicit syncronization happening on some chan/mutex somewhere purely by accident), 

I've stumbled upon this while working on validator-registrations (and we also discussed this with **olegshmuelov** [here](https://github.com/ssvlabs/ssv-spec/issues/504#issuecomment-2786836545)) -  https://github.com/ssvlabs/ssv/pull/2130#discussion_r2135249089 - the TLDR is that we better get rid of all `r.GetShare().FeeRecipientAddress` usages and rely on **storage** (that has mutex-based syncronization for reads/writes we can rely on) to fetch the up-to-date fee-recipient instead

File: protocol/v2/ssv/runner/proposer.go [hunk 2]
```diff
@@ -190,6 +192,41 @@ func (r *ProposerRunner) ProcessPreConsensus(ctx context.Context, logger *zap.Lo
...
+
+		if err = r.GetBeaconNode().SubmitProposalPreparation(ctx, feeRecipients); err != nil {
+			span.RecordError(err)
+			logger.Warn("failed to submit proposal preparation, continuing with original block data", zap.Error(err))
+		} else {
+			obj, ver, err = r.GetBeaconNode().GetBeaconBlock(ctx, duty.Slot, r.graffiti, fullSig)
+			if err != nil {
+				span.RecordError(err)
+				logger.Warn("failed to get beacon block after proposal preparation, continuing with original block data", zap.Error(err))
```
Comment (iurii-ssv) [inline protocol/v2/ssv/runner/proposer.go]: I think here logging at `Error` level is more appropriate

Also, I think `obj` will be overwritten with whatever that 2nd `.GetBeaconBlock` call returns - so we won't be able to `"continuing with original block data"` (need to adjust that I guess)

File: protocol/v2/ssv/runner/proposer.go [hunk 3]
```diff
@@ -190,6 +192,41 @@ func (r *ProposerRunner) ProcessPreConsensus(ctx context.Context, logger *zap.Lo
...
+	if summarizeErr == nil && blockSummary.FeeRecipient == (bellatrix.ExecutionAddress{}) {
+		logger.Warn("fee recipient missing from beacon block, resubmitting proposal preparation")
+
+		feeRecipients := map[phase0.ValidatorIndex]bellatrix.ExecutionAddress{
+			r.GetShare().ValidatorIndex: r.GetShare().FeeRecipientAddress,
+		}
+
+		if err = r.GetBeaconNode().SubmitProposalPreparation(ctx, feeRecipients); err != nil {
+			span.RecordError(err)
+			logger.Warn("failed to submit proposal preparation, continuing with original block data", zap.Error(err))
```
Comment (iurii-ssv) [inline protocol/v2/ssv/runner/proposer.go]: I think here logging at `Error` level is more appropriate,

- plus I think `.SubmitProposalPreparation` request needs to have a very strict timeout on it (maybe ~1s at most) - due to how time-constrained block-proposal duty is
- also, are we sure this will even work ? CLs might not update their fee-recipients immediately after `.SubmitProposalPreparation` request is done (maybe they update it periodically in batches, for example)

File: protocol/v2/ssv/runner/proposer.go [hunk 4]
```diff
@@ -190,6 +192,41 @@ func (r *ProposerRunner) ProcessPreConsensus(ctx context.Context, logger *zap.Lo
 		observability.BeaconBlockIsBlindedAttribute(blockSummary.Blinded),
 	))
 
+	// Check if the block has a fee recipient. If not, submit preparations and try again.
```
Comment (iurii-ssv) [inline protocol/v2/ssv/runner/proposer.go]: I think now that block-fetching became so complicated - we might want to create a helper-func for it, WDYT ? I wish we could get rid of some `else`-clauses as well, maybe that could also help with that

**Review by iurii-ssv — COMMENTED** [review]
Interesting discovery, however I'm not sure this is the right way to approach this ...

SSV cluster has ~4s to propose block, and the later we can "request the block from block-builders" the better MEV we'll get (we even added `ProposerDelay` functionality recently to allow operators to delay block-fetch request as much as possible); While the functionality added in this PR is technically beneficial for MEV (there is a chance we'll fetch block later) the fact that's it's probabilistic is problematic because:
- it makes `ProposerDelay` setting less viable in general (eg. previously you could set it at 1s, now if you do that occasionally you'd end up waiting for too long with those added CL requests on top and fail the block proposal duty entirely), meaning we'd need to lower the "recommended safe value" for it by the ~99th percentile time it takes for these 2 additional requests to execute ... or just accept the risk of failing block-proposal duty
- it also makes our QBFT way less reliable because of the fact that every Operator starts QBFT instance at different times (so, some Operators will make those additional CL requests and start it later) and enters round-change exactly 2s after that - meaning some Operators might start round-change way sooner than others, and this I think could lead to round-1 never succeeding while round-change also never succeeds (or if it does, it's an unnecessary round-change)

maybe what we should consider doing instead is (maybe as long-term solution since it might have some caveats to it, and we'll need to do a lot of testing for it as well to make sure it's stable):
- request block from ALL the CL clients SSV node is connected to in parallel
- terminate all those requests at some reasonably low deadline (perhaps 2s after slot-start time) and check what results we got and pick the best one (I guess for now we can only compare blocks for fee-recipient presence, but maybe also prefer fresher blocks for higher MEV); This would be similar to how WAD works, I believe
- the question is what deadline to pick, on one hand we must have some block to propose (only if we are the Leader btw) and on the other hand if the deadline it too large we won't have enough time for a round-change; IMO we should implement 2 opposite options validator could choose between in SSV config: 1) prioritize duty execution safety over MEV and 2) prioritize MEV as much as possible (there will be no round-change, all 4s are allocated to get the block built at the latest moment possible)

**Comment by nkryuchkov** [comment]
@iurii-ssv @y0sher 

I have rewritten the logic. Please review the latest changes.

New logic:
- get a proposal from all nodes and select one with a fee recipient or the first one if none
- re-submit the latest registrations on reconnection to CL
- submit preparations and request a new proposal with a strict deadline for a single client if the proposal has no fee recipient (unlikely but possible)

The proposal choice method is huge now, and there are no tests, but I don't want to do it until we decide on the algorithm we use and make sure it works

**Comment by nkryuchkov** [comment]
@greptileai please review the latest changes

File: beacon/goclient/proposer.go [hunk 5]
```diff
@@ -319,7 +310,473 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+	proposals := make(chan *api.VersionedProposal, len(gc.clients))
+
+	var wg sync.WaitGroup
+
+	requestCtx, requestCancel := context.WithCancel(ctx)
+	defer requestCancel()
+
+	for _, client := range gc.clients {
+		wg.Add(1)
+		go func() {
```
[the remark this answers is not in the document]
Comment (nkryuchkov) [reply beacon/goclient/proposer.go]: @greptileai hasn't it been fixed in Go 1.22?

File: beacon/goclient/proposer.go [hunk 6]
```diff
@@ -61,12 +64,8 @@ func (gc *GoClient) GetBeaconBlock(
...
 	reqStart := time.Now()
-	proposalResp, err := gc.multiClient.Proposal(ctx, &api.ProposalOpts{
-		Slot:                   slot,
-		RandaoReveal:           sig,
-		Graffiti:               graffiti,
-		SkipRandaoVerification: false,
-	})
+
+	beaconBlock, err := gc.getProposal(ctx, slot, graffitiBytes, randao)
 	recordRequestDuration(ctx, "Proposal", gc.multiClient.Address(), http.MethodGet, time.Since(reqStart), err)
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: We should probably change the way we measure request duration now (the `recordRequestDuration` call should probably be made per-client - similar to [how it's done for WAD](https://github.com/ssvlabs/ssv/blob/c0842d0cb32f802248e35841020895d29f1a3a10/beacon/goclient/attest.go#L306-L306))

File: beacon/goclient/proposer.go [hunk 7]
```diff
@@ -319,7 +310,481 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+			// or hasFeeRecipient doesn't count all cases.
+			// So we just log it, return the block we received,
+			// and let the caller decide what to do with it.
+			logger.Warn("failed to check fee recipient", zap.Error(err))
+			return p.Data, nil
+		}
+
+		if b {
+			return p.Data, nil
+		}
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: Nit: reads better like this IMO (and in other similar places too):
```go

		ok, err := hasFeeRecipient(p.Data)
		if err != nil {
			// If we cannot check fee recipient, either the block is malformed
			// or hasFeeRecipient doesn't count all cases.
			// So we just log it, return the block we received,
			// and let the caller decide what to do with it.
			logger.Warn("failed to check fee recipient", zap.Error(err))
			return p.Data, nil
		}
		if ok {
			return p.Data, nil
		}
```

File: beacon/goclient/proposer.go [hunk 8]
```diff
@@ -319,7 +310,481 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+			return nil, err
+		}
+
+		b, err := hasFeeRecipient(p.Data)
+		if err != nil {
+			// If we cannot check fee recipient, either the block is malformed
+			// or hasFeeRecipient doesn't count all cases.
+			// So we just log it, return the block we received,
+			// and let the caller decide what to do with it.
+			logger.Warn("failed to check fee recipient", zap.Error(err))
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: I think we'd want to log this as `Error` since both root-causes you mention count as error that needs looking into, in my book :)

File: beacon/goclient/proposer.go [hunk 9]
```diff
@@ -319,7 +310,481 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+
+		if b {
+			return p.Data, nil
+		}
+
+		feeRecipients := gc.feeRecipientsCache.Load()
+		if feeRecipients == nil {
+			// The cache shouldn't be empty because proposal preparations are submitted on the node start,
+			// but it's better to check it to avoid nil pointer dereference.
+			logger.Warn("received a proposal without fee recipients but the fee recipients data hasn't been built yet")
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: Similar to `Warn` from above, I would log this as `Error`,

I guess applies to a bunch of other errors currently logged as `Warn` in this PR (some are fine under `Warn` I guess, but there are plenty others I would classify as `Error`)

File: beacon/goclient/proposer.go [hunk 10]
```diff
@@ -319,7 +310,481 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+		}
+
+		// Although proposal preparations are submitted on client restart,
+		// the client may return no fee recipient because we submit them
+		// in batches and don't interrupt the process on error.
+		// So, given the load on the node on restart, it's possible
+		// that registrations haven't been submitted, although it's unlikely.
+		// Therefore, we can afford to try to submit them again
+		// and request another block using a strict deadline.
+		logger.Warn("received a proposal without fee recipients, trying to submit a preparation and get a new one")
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: Maybe to clarify:
- `on client restart` -> `on Beacon node restart`
- `the client may return no fee recipient because we submit them` -> `the Beacon node may return no fee recipient because we submit proposal preparations`
- `Therefore, we can afford to try to submit them again` -> `Therefore, we may have to try to submit them again`
- `and request another block using a strict deadline.` -> `and request another block using a strict deadline that will, hopefully, have fee recipient set.`

File: beacon/goclient/proposer.go [hunk 11]
```diff
@@ -319,7 +310,481 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+		select {
+		case <-preparationsCtx.Done():
+			logger.Warn("preparation submission and requesting new proposal timed out, using the first received proposal")
+			return p.Data, nil
+		case proposal, ok := <-proposalCh:
+			if !ok {
+				// The error should have already been logged.
+				logger.Warn("failed to submit preparation submission and request a new proposal")
+				return p.Data, nil
+			}
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: Nit: I think it's cleaner to send `error` over `chan` (a separate special channel to handle error-cases) and log it once at the receiver side (instead of having a bunch of logger-calls all over the place + this one here as well)

But if that gets tricky to re-write ... maybe don't bother (since for many-clients scenario you'd probably also need to re-write this to keep things consistent)

File: beacon/goclient/proposer.go [hunk 12]
```diff
@@ -319,7 +310,481 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+	// Although we re-submit proposal preparation on client restart,
+	// the spec doesn't guarantee it will be used:
+	//
+	// https://ethereum.github.io/beacon-APIs/#/Validator/prepareBeaconProposer
+	// > Note that there is no guarantee that the beacon node will
+	// > use the supplied fee recipient when creating a block proposal,
+	// > so on receipt of a proposed block the validator should confirm
+	// > that it finds the fee recipient within the block acceptable before signing it.
+	//
+	// So we nevertheless try to find a proposal with a fee recipient.
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: I think it's better to place this comment next to the one from above (that starts with `// Although proposal preparations are submitted on client restart`) because they are explaining the same thing from different angles,

but it's not like having 1 or many clients changes anything with respect to things these comments mention

**edit:** actually this part about "spec doesn't guarantee" probably applies only to 1-client case where we try to send additional prepare-proposal + fetch-new-block requests (but currently it's placed right next to many-clients code-block for some reason)

File: beacon/goclient/proposer.go [hunk 13]
```diff
@@ -319,7 +310,481 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+		// the client may return no fee recipient because we submit them
+		// in batches and don't interrupt the process on error.
+		// So, given the load on the node on restart, it's possible
+		// that registrations haven't been submitted, although it's unlikely.
+		// Therefore, we can afford to try to submit them again
+		// and request another block using a strict deadline.
+		logger.Warn("received a proposal without fee recipients, trying to submit a preparation and get a new one")
+
+		deadline := gc.beaconConfig.GetSlotStartTime(gc.beaconConfig.EstimatedCurrentSlot()).
+			Add(gc.beaconConfig.SlotDuration / 4) // TODO: find the best value
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: So, `slot_start + 3s` is not the best because the QBFT round 1 times out at `slot_start + 2s`, meaning this might result in an operator joining QBFT no sooner than round 2 (and half-way into round 2 as well),

although there isn't a clear universally good deadline value I would maybe lower it down to `slot_start + 2s` so that we at least can join the round 2 at the start of the round and thus have higher chance to finish QBFT (also because in a cluster of 4 there is a ~75% chance we are not even gonna be a leader for round 2)

**update:** on the other hand, IF we are gonna rely on QBFT finishing in under ~700ms anyway (as [mentioned in this tread](https://github.com/ssvlabs/ssv/pull/2415#discussion_r2245043253) below) we might as well set the deadline to `slot_start + 3.3s`

File: beacon/goclient/proposer.go [hunk 14]
```diff
@@ -319,7 +310,481 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+
+		preparationsCtx, cancel := context.WithDeadline(ctx, deadline)
+		defer cancel()
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: I would rename `preparationsCtx` -> `requestCtx` so that it's clear that this context covers not only preparations-request but also proposal-fetch-request as well

File: beacon/goclient/proposer.go [hunk 15]
```diff
@@ -319,7 +310,481 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+				Slot:                   slot,
+				RandaoReveal:           sig,
+				Graffiti:               graffiti,
+				SkipRandaoVerification: false,
+			})
+
+			if err != nil {
+				gc.log.Warn("failed to get proposal", fields.Address(client.Address()), zap.Error(err))
+				return
+			}
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: I think we need to avoid unnecessary newlines and keep `if err != nil` as close as possible to the place where it originates:
- this is simply because it's better to use newlines to separate out large chunks of functionality in big functions like this one
- and I think this is more consistent with Golang coding guidelines (and the rest of our code-base) in general

File: beacon/goclient/proposer.go [hunk 16]
```diff
@@ -319,7 +310,481 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+				return p, nil
+			}
+
+			// We don't have any proposals, so we got some error.
+			// The errors have been logged, so we don't need to return them.
+			return nil, fmt.Errorf("all requests failed")
+		}
+		// Got a proposal with fee recipient. It is good enough, we can use it.
+		return p, nil
+	case <-ctx.Done():
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: I think we should use `case <-requestCtx.Done():` here (and below this clause),

but since we are not setting any deadline/timeout for `requestCtx` might as well get rid of `requestCtx` entirely (I'm not sure if we want to have any),

Still, we have another problem here - because we don't set deadline/timeout for `requestCtx` and due to how this whole `select` is written - we are waiting (perpetually with no explicit deadline/timeout) until all `.Proposal` requests finish.

So, what I think we should do instead is have a concept of "soft-deadline" (similar to how we have it for WAD):
- we poll both channels `proposals` and `proposalsWithFeeRecipient`
- if there is an available result on `proposalsWithFeeRecipient` - we always return it
- if no results on `proposalsWithFeeRecipient` has arrived by the time "soft-deadline" is reached we must return any result we received on `proposals` channel

I would set "soft-deadline" to `slot_start + 1.3s`, the idea being:
- QBFT round 1 times out at `slot_start + 2s` - so we need to give round 1  enough time to complete
- looking at our main production cluster I think I saw ~99% of QBFTs end in under 350ms
- 2x that number to account for not-so-stable infra 3rd party Operators might have and this gives us a reasonably safe estimate of ~700ms for QBFT to complete in 99% of the cases - which translates into `slot_start + 1.3s`

Also, we don't have any deadline / timeout for the whole block-fetching algorithm (call it "hard deadline") ... on one hand we could set "hard deadline" = 2s and be able to participate in QBFT round 2 (which is good most of the times - the times we are not a leader), on the other hand if we are a Leader we probably should have waited more (since round 2 will fail with 100% certainty now because we have no block). Thinking a bit more about it I would set "hard deadline" to `slot_start + 3.3s` (similar to this case - https://github.com/ssvlabs/ssv/pull/2415#discussion_r2244998387 - we should probably just use the same `ctx` object for both with `slot_start + 3.3s` deadline on it)

File: beacon/goclient/proposer.go [hunk 17]
```diff
@@ -319,7 +310,481 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+
+		err := gc.multiClientSubmit(ctx, "SubmitProposalPreparations", func(ctx context.Context, client Client) error {
+			return client.SubmitProposalPreparations(ctx, batch)
+		})
+		if err != nil {
+			gc.log.Warn("could not submit proposal preparation batch",
+				zap.Int("start_index", start),
+				zap.Error(err),
+			)
+			continue
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: While at it, I think we should log this as `Error` (not `Warn`)

File: beacon/goclient/goclient.go [hunk 18]
```diff
@@ -170,6 +171,8 @@ type GoClient struct {
 	// voluntaryExitDomainCached is voluntary exit domain value calculated lazily and re-used
 	// since it doesn't change over time
 	voluntaryExitDomainCached atomic.Pointer[phase0.Domain]
+
+	feeRecipientsCache atomic.Pointer[map[phase0.ValidatorIndex]bellatrix.ExecutionAddress]
```
Comment (iurii-ssv) [inline beacon/goclient/goclient.go]: I would add a comment for this field to describe why we need it:
```go
// feeRecipientsCache is used during certain scenarios to re-populate fee recipient data that Beacon node might lose due to restart.
```

**Review by iurii-ssv — COMMENTED** [review]
The updated solution pretty much looks exactly like what I had in mind, left some comments we might need to address (mostly nits, but [this one in particular](https://github.com/ssvlabs/ssv/pull/2415#discussion_r2245043253) is important to fix).

Also, I think we maybe should address these as well in this PR (for completeness) from https://github.com/ssvlabs/ssv/issues/2408 (and probably close that issue after that since this PR targets pretty much all actionable items in there):
- `ProposerValueCheckF` (value check for consensus data) - check if the address is the same as the configured one. Can be addressed immediately
- stuff under **Gaps in Our Current Logic** section

**Comment by nkryuchkov** [comment]
> Also, I think we maybe should address these as well in this PR (for completeness) from #2408 (and probably close that issue after that since this PR targets pretty much all actionable items in there):
> 
> * `ProposerValueCheckF` (value check for consensus data) - check if the address is the same as the configured one. Can be addressed immediately
> * stuff under **Gaps in Our Current Logic** section

yes, I want to make sure we agree on the algorithm first

File: beacon/goclient/proposer.go (hunk 11 above)
Comment (nkryuchkov) [reply beacon/goclient/proposer.go]: Well, I decided to implement it like this because the goroutine closes `proposalCh` (I think a channel writer should always close the channel), so when the goroutine terminates, `select` might read from `proposalCh` first. So anyway, we'd need to handle `proposalCh` closure as an error, therefore I thought the error channel would be redundant

File: beacon/goclient/proposer.go (hunk 12 above)
Comment (nkryuchkov) [reply beacon/goclient/proposer.go]: They are explaining a bit different things (for single and multi client) caused by the same thing. I tried to merge them into a comment above the function declaration but it was quite heavy to read, so I felt it's easier to read them both right where they belong to

File: beacon/goclient/proposer.go (hunk 16 above)
Comment (nkryuchkov) [reply beacon/goclient/proposer.go]: > I think we should use `case <-requestCtx.Done():` here (and below this clause),

`requestCtx` is just a wrapper that's canceled when the method finishes to cancel the spawned goroutines to avoid waiting for the parent context timeout. So, if we change it inside the `select`, it won't change anything: it still will be canceled only when the parent context is canceled. I think checking that all requests are finished by checking if proposal channels are closed is quite reliable.

> Also, we don't have any deadline / timeout for the whole block-fetching algorithm (call it "hard deadline") ... on one hand we could set "hard deadline" = 2s and be able to participate in QBFT round 2 (which is good most of the times - the times we are not a leader), on the other hand if we are a Leader we probably should have waited more (since round 2 will fail with 100% certainty now because we have no block). Thinking a bit more about it I would set "hard deadline" to `slot_start + 3.3s` (similar to this case - [#2415 (comment)](https://github.com/ssvlabs/ssv/pull/2415#discussion_r2244998387) - we should probably just use the same `ctx` object for both with `slot_start + 3.3s` deadline on it)

I'm not sure we need the "hard" deadline here. If we didn't get anything 3.3s after the slot start, we can't do much with it. I think there aren't any benefits if we just return over trying to wait more. But if we get it a bit later, there's still a chance for submission

File: beacon/goclient/proposer.go (hunk 13 above)
Comment (nkryuchkov) [reply beacon/goclient/proposer.go]: changed to 1.3s

File: beacon/goclient/proposer.go (hunk 12 above)
Comment (iurii-ssv) [reply beacon/goclient/proposer.go]: The comment with `https://ethereum.github.io/beacon-APIs/#/Validator/prepareBeaconProposer` doesn't belong in `getProposalStreams` func because it just isn't relevant to any of the code in there (and we don't submit preparations in multi-client case) ?

Seems like it should be in `getSingleClientProposal` (and grouping with another comment just seems logical to keep the whole rationale for what `getSingleClientProposal` is doing in one place, maybe it can be trimmed but I don't mind large comments ... it's better than no comments, and  grouping comments any other way that makes sense I don't mind either as long as it's not misplaced - which seems to be the case here).

Or maybe I'm missing something.

File: beacon/goclient/proposer.go (hunk 16 above)
Comment (iurii-ssv) [reply beacon/goclient/proposer.go]: > `requestCtx` is just a wrapper that's canceled when the method finishes to cancel the spawned goroutines to avoid waiting for the parent context timeout.

Oh right, that a valid reason to have a separate context object created.

> I think checking that all requests are finished by checking if proposal channels are closed is quite reliable.

The problem I'm describing above is not with readability but with the fact that we have to wait for channel-close (which may happen very late if we are not getting blocks with fee-recipients on them, but instead getting blocks with 0-fee-recipients only ... since we don't even have a "hard deadline" set we might wait for more than 4s) - so I'm suggesting to define a "soft-deadline" to make sure code never gets stuck in that manner (and returns 0-fee-recipient at some point instead).

Now you've added `feeRecipientCtx` (deadlining at `slot_start + 1.3s`) - it  is essentially the same thing as "soft-deadline" I'm talking about. I just wish we can [simplify the code like I suggested below](https://github.com/ssvlabs/ssv/pull/2415#discussion_r2249185032).

Comment (iurii-ssv) [reply beacon/goclient/proposer.go]: As for the "hard deadline", the benefit of having it is that we will start QBFT instance guaranteed (lets say at 3.3s after slot start). And to put concrete numbers to it, in a cluster of 4 nodes we'll have a 75% chance that we didn't even need the block we are trying to fetch here AT ALL - as [explained in this comment](https://github.com/ssvlabs/ssv/blob/a1943433ecddc813d5da6bdfde6db081193ebd47/protocol/v2/ssv/runner/proposer.go#L163-L165) because our role would just be to approve the block proposed by another Operator  (it is unfortunate how "QBFT instance starting" is currently implemented - but I've described it in more detail [here](https://github.com/ssvlabs/ssv/issues/1825)). If we don't have any "hard deadline" we will never start QBFT instance in some cases in time to participate in QBFT consensus (essentially raising the chance for QBFT to fail).

That said, by setting "hard deadline" (to `slot_start + 3.3s` for example) we are taking a trade-off of not having a block at all while we might need it (the 25% case). So maybe we shouldn't set any hard deadline for now and just get back to it if/when we can we have a more comprehensive solution (that will address https://github.com/ssvlabs/ssv/issues/1825 in full).

I'm just listing all the relevant considerations this code revolves around for future reference (so we can get back to it later if we need to).

File: beacon/goclient/proposer.go [hunk 19]
```diff
@@ -319,7 +307,578 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+
+	proposalPreparation := map[phase0.ValidatorIndex]bellatrix.ExecutionAddress{
+		validatorIndex: address,
+	}
+
+	// Although SubmitProposalPreparation is designed for a multi client,
+	// we can reuse it for a single client to avoid code duplication.
+	if err := gc.SubmitProposalPreparation(ctx, proposalPreparation); err != nil {
+		return nil, fmt.Errorf("submit proposal preparation: %w", err)
+	}
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: But to fetch proposal for single-client case we are doing `gc.clients[0].Proposal` ... That inconsistency is probably something we want to address (I would maybe use `gc.clients[0]` everywhere but maybe there is a better way)

File: beacon/goclient/proposer.go [hunk 20]
```diff
@@ -319,7 +307,578 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+			gc.log.Debug("received a proposal with fee recipient")
+			return p, nil
+		case p, ok := <-selectProposalCh:
+			// Didn't get a proposal with fee recipient until feeRecipientCtx expired,
+			// so we are ready to accept any proposal.
+			if !ok {
+				// We don't have any proposals, so we got some error.
+				// The errors have been logged, so we don't need to return them.
+				return nil, fmt.Errorf("all requests failed")
+			}
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: Since we never `close(selectProposalCh)` I don't think checking for `!ok` value does something ? We'll:
- either just block on this channel
- or get some value out of it with `ok == true`

So I'm not sure what the intention was here ... overall this whole "for-select" construction is kinda scary, I wonder if we could simplify it ... I came up with [this implementation](https://github.com/ssvlabs/ssv/commit/4684135dd5d41a4d21152af8a18417065554ef7b) - hope you find it useful, note:
- I think it does everything we need it to do
- I was able to remove most of the comments since the code is simple and self-explanatory now, I believe
- there is no need to `close` channels, they are garbage-collected automatically eventually, and we don't need to know when ALL requests ended (timeouts take care of everything for us)
- [and just general thoughts on `<-ctx.Done()`] once we are falling under `<-ctx.Done()` case there is really no need to check for the presence of proposal on other channels we are selecting on ... I know that select is "not sequential" in a sense that we still might have some values on those channels ready and go scheduler will still choose the done-clause anyway sometimes, but that's so unlikely that it's just not worth complicating our code for (it only makes sense to do this if our context-timeout is comparable to the time it takes for go scheduler to "check on those channels" which is probably ~10ms at most, likely 1ms or less,  because then the chance of context-timeout is just too large to ignore while also having ready-available proposal value at the same time ... but that's not the case here)

File: beacon/goclient/proposer.go (hunk 13 above)
Comment (iurii-ssv) [reply beacon/goclient/proposer.go]: Yeah, `slot_start + 1.3s` is another "sort-of good option", it just makes different trade-offs. I think it's okay, but IMO:
- we should use `slot_start + 1.3s` for multi-client case, like you are already doing
- we should use `slot_start + 3.3s` for single-client case because it sends 2 requests on top of the original block-fetch request (and also keep in mind that proposer-runner spends time to create RANDAO prior to all that which takes maybe additional ~300ms) ... I just doubt that `1.3s` is enough to accommodate all of this

File: beacon/goclient/proposer.go (hunk 12 above)
Comment (nkryuchkov) [reply beacon/goclient/proposer.go]: The comment refers to getting proposals on client reconnection. It just explains that submission on client reconnection doesn't guarantee we will get a proposal with a correct fee recipient, therefore, it tries to get a proposal from several nodes and chooses the best one

File: beacon/goclient/proposer.go (hunk 16 above)
Comment (nkryuchkov) [reply beacon/goclient/proposer.go]: Regarding the hard deadline, what would we return if we didn't get any proposal until 3.3s? If it's an error, we currently don't start a consensus on failure to get a proposal, so I guess it won't change the behavior unless we change the error handling of the `r.GetBeaconNode().GetBeaconBlock` call

File: beacon/goclient/proposer.go (hunk 20 above)
Comment (nkryuchkov) [reply beacon/goclient/proposer.go]: We close it, it references `proposals` channel. Initially, `selectProposalCh` is nil, which disables its select case. Then, on timeout, we assign it to `proposals`

Comment (nkryuchkov) [reply beacon/goclient/proposer.go]: I checked your suggestion, it looks good, but I think it waits for the timeout if all goroutines fail — that's why I check the channel closure. Although, I agree that the code could look simpler

Comment (nkryuchkov) [reply beacon/goclient/proposer.go]: I added some unit tests to make sure refactors don't break the logic

File: beacon/goclient/proposer.go (hunk 16 above)
Comment (iurii-ssv) [reply beacon/goclient/proposer.go]: Yeah, we'd need to adjust our code so it would get a "dummy/nil" block in that case. I'm leaning towards having no "hard deadline" for now though to keep things simple (and it's also out of the scope of this PR, I just wanted to add some notes on this in case we get back to it in the future).

File: beacon/goclient/proposer_test.go [hunk 21]
```diff
@@ -0,0 +1,213 @@
...
+		})
+	}
+}
+
+func sleep(t *testing.T, duration time.Duration) {
+	select {
+	case <-t.Context().Done():
+	case <-time.After(duration):
+	}
+}
```
Comment (iurii-ssv) [inline beacon/goclient/proposer_test.go]: I'm not sure this does anything, could you clarify ? From what I understand about `t.Context()` - it's just a helper method we can use in tests to "plug the holes" and don't create our own context object ... I would simply use `time.Sleep` instead

maybe it can help us terminate a test that's "killed with an external signal" - but even if it works like that I don't think the added code/complexity (compared vs `time.Sleep`) is worth it ... it's not like we are sleeping for minutes

File: beacon/goclient/proposer_test.go [hunk 22]
```diff
@@ -0,0 +1,213 @@
...
+			beaconCfg := *networkconfig.TestNetwork.BeaconConfig
+			beaconCfg.GenesisTime = time.Now()
+
+			gc := &GoClient{
+				log:          logging.TestLogger(t),
+				beaconConfig: &beaconCfg,
+			}
+
+			proposals := make(chan *api.VersionedProposal, len(tc.frProposals))
+			frProposals := make(chan *api.VersionedProposal, len(tc.proposals))
```
Comment (iurii-ssv) [inline beacon/goclient/proposer_test.go]: Those `len` params seem to be in the wrong order ? 

Also, maybe we should have a test that sends multiple proposals/frProposals on the channel (seems like currently we are sending 1 at most) ? I would add some delay between those sends as well (maybe ~100ms) to simulate how it works in the real world more closely.

File: beacon/goclient/proposer_test.go [hunk 23]
```diff
@@ -0,0 +1,213 @@
...
+
+func TestGoClient_selectBestProposal(t *testing.T) {
+	tt := []struct {
+		name         string
+		ctxTimeout   time.Duration
+		frProposals  []uint64 // IDs; must be unique
+		frDelay      time.Duration
+		proposals    []uint64 // IDs; must be unique
+		pDelay       time.Duration
+		wantProposal uint64
```
Comment (iurii-ssv) [inline beacon/goclient/proposer_test.go]: Is `wantProposal uint64` supposed to be an ID ? Maybe leave a comment about that (to be consistent with the rest of the comments above)

File: beacon/goclient/proposer_test.go [hunk 24]
```diff
@@ -0,0 +1,213 @@
...
+			)
+
+			if tc.wantErr != "" {
+				require.ErrorContains(t, err, tc.wantErr)
+			} else {
+				require.NoError(t, err)
+				require.EqualValues(t, tc.wantProposal, proposal.ConsensusValue.Uint64())
+			}
+			require.GreaterOrEqual(t, time.Since(beaconCfg.GenesisTime), tc.wantDelay)
+			require.LessOrEqual(t, time.Since(beaconCfg.GenesisTime), tc.wantDelay+10*time.Millisecond)
```
Comment (iurii-ssv) [inline beacon/goclient/proposer_test.go]: I think the `require.GreaterOrEqual` is good to have but `require.LessOrEqual` check will likely be flaky,

we should either remove it or at least change `tc.wantDelay+10*time.Millisecond` -> `tc.wantDelay+100*time.Millisecond` (although CI might still easily "lag" for more than 100ms) ... so I don't think we should be "checking for go-scheduler dependent things because they are out of our control"

File: beacon/goclient/proposer.go [hunk 25]
```diff
@@ -319,7 +225,673 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+				// Probably, there are some connection issues or the node is overloaded.
+				return nil, ctx.Err()
+			}
+		}
+	}
+}
+
+// latestProposalTime returns the latest time when QBFT should start
+// to have a high chance to finish within the best time range for given slot.
+func (gc *GoClient) latestProposalTime(slot phase0.Slot, maxRound qbft.Round) time.Time {
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: `within the best time range for given slot` -> `within the best time range for given slot and round`

File: beacon/goclient/proposer.go [hunk 26]
```diff
@@ -319,7 +225,673 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+			// Got a proposal with fee recipient. It is good enough, we can use it.
+			gc.log.Debug("received a proposal with fee recipient")
+			return p, nil
+		case p, ok := <-selectProposalCh:
+			// Didn't get a proposal with fee recipient until feeRecipientCtx expired,
+			// so we are ready to accept any proposal.
+			if !ok {
+				// We don't have any proposals, so we got some error.
+				// The errors have been logged, so we don't need to return them.
+				return nil, fmt.Errorf("all requests failed")
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: The way I read it, if we end up doing `return nil, fmt.Errorf("all requests failed")` - it doesn't necessarily mean that all requests fail,

we could have gotten some value on `proposalsWithFeeRecipient` channel but simply didn't have enough time to read it (due to `select` choosing the `case p, ok := <-selectProposalCh:` branch over `case p, ok := <-proposalsWithFeeRecipient:` one),

maybe we could check if `proposalsWithFeeRecipient` has anything on it before returning this error (akin to how you are handling a similar situation in `case p, ok := <-proposalsWithFeeRecipient:` branch)

File: beacon/goclient/proposer.go [hunk 27]
```diff
@@ -319,7 +225,673 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+				// If we have one without fee recipient, it's better that nothing, so we use it.
+				gc.log.Warn("no proposals with fee recipient found")
+				return p, nil
+			default:
+				// We still don't have any proposals, but requests haven't finished yet.
+				// However, we don't have more time, so we have to return an error.
+				// Probably, there are some connection issues or the node is overloaded.
+				return nil, ctx.Err()
+			}
+		}
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: I think if we want to check on `case p, ok := <-proposals:` we also want to check on `case p, ok := <-proposalsWithFeeRecipient:`, no ?

IMO we shouldn't even bother with these checks due to how low of a probability this situation is (like I mentioned in [another comment, general thoughts on `<-ctx.Done()`](https://github.com/ssvlabs/ssv/pull/2415#discussion_r2249185032)) - but if we do want to handle that we probably want to cover all possible cases

File: beacon/goclient/proposer.go (hunk 20 above)
Comment (iurii-ssv) [reply beacon/goclient/proposer.go]: >  think it waits for the timeout if all goroutines fail — that's why I check the channel closure.

Right, it does assume `ctx`is actually a request-context with some sort of reasonable deadline on it - "hard deadline" discussed in another tread (but it doesn't have to be a small value, it could be 4s - after 4s there is no need to participate in block-proposal duty ... we just need this deadline to "release this go-routine from select, and release the resources"). So we'd want to update that part, I agree.

> I added some unit tests to make sure refactors don't break the logic

Good to have them, still when it comes to concurrent code I would say it's hard-to-impossible to cover all the possibilities (in other words - I wouldn't be able to confidently say "concurrent code is fine IF it's covered by a reasonable test-suite")

> I checked your suggestion, it looks good, but I think it waits for the timeout if all goroutines fail — that's why I check the channel closure. Although, I agree that the code could look simpler

So, looking into it some more - I think the way you wrote it is interesting and should work OK, but still
- unrolling the loop like in my example from above is just simpler to work with overall (to understand what it does and update if necessary later on)
- and there are potentially [things like these](https://github.com/ssvlabs/ssv/pull/2415#discussion_r2253828840) that I'm not sure if it's a bug/edge-case  or I'm reading it wrong (either way is not ideal tho)

File: beacon/goclient/proposer_test.go (hunk 22 above)
Comment (nkryuchkov) [reply beacon/goclient/proposer_test.go]: Yes, I swapped their order and forgot to change the length. Thanks

File: beacon/goclient/proposer_test.go (hunk 21 above)
Comment (nkryuchkov) [reply beacon/goclient/proposer_test.go]: It's canceled on test termination: https://github.com/golang/go/blob/master/src/testing/testing.go#L1557

But probably it's not worth it, yeah

File: beacon/goclient/proposer.go (hunk 27 above)
Comment (nkryuchkov) [reply beacon/goclient/proposer.go]: I agree that the case when the proposals channel gets closed after the timeout is very rare, but if it happens, the code will return a nil proposal, which will likely lead to panic, so I think we need the check

Comment (iurii-ssv) [reply beacon/goclient/proposer.go]: > but if it happens, the code will return a nil proposal, which will likely lead to panic, so I think we need the check

Don't we return `error` in that case (so that even if proposal is `nil` it's never checked & treated as something valid) ?

Comment (nkryuchkov) [reply beacon/goclient/proposer.go]: > > but if it happens, the code will return a nil proposal, which will likely lead to panic, so I think we need the check
> 
> Don't we return `error` in that case (so that even if proposal is `nil` it's never checked & treated as something valid) ?

Sorry, I just realized I wasn't clear enough, it was a reply to this:

> IMO we shouldn't even bother with these checks due to how low of a probability this situation is 

I'd remove these checks if it didn't change the behavior, but it can lead to a nil proposal.

In other words, if we had something like this

```go
			case p := <-proposals:
				// If we have one without fee recipient, it's better that nothing, so we use it.
				gc.log.Warn("no proposals with fee recipient found")
				return p, nil
```

then `p` could potentially be `nil`

Comment (iurii-ssv) [reply beacon/goclient/proposer.go]: Hmm, but I'm not suggesting to "remove just the **ok** part" in the `case p, ok := <-proposals:` clause (so it becomes `case p := <-proposals:`) - we need to handle the channel closure there for sure,

I'm suggesting to remove the whole `case p, ok := <-proposals:` clause entirely because it's very unlikely we hit it in practice once the context has been canceled (it's below 0.1% in my estimates, so it's pretty safe to neglect it). Just because it makes the code a bit harder to read.

But if you want to handle it still - it's okay by me, just need to account for all the cases (the `case p, ok := <-proposalsWithFeeRecipient:` need to be checked also, I think)

File: beacon/goclient/proposer.go (hunk 26 above)
Comment (nkryuchkov) [reply beacon/goclient/proposer.go]: I rewrote the function to use one channel instead, so I guess it's not relevant anymore

File: beacon/goclient/proposer.go (hunk 27 above)
Comment (nkryuchkov) [reply beacon/goclient/proposer.go]: I rewrote the function to use one channel instead, so I guess it's not relevant anymore

File: beacon/goclient/proposer.go (hunk 20 above)
Comment (nkryuchkov) [reply beacon/goclient/proposer.go]: I rewrote the function to use one channel instead, so I guess it's not relevant anymore

File: beacon/goclient/proposer.go [hunk 28]
```diff
@@ -319,7 +225,651 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+	proposalCh chan *api.VersionedProposal,
+) (*api.VersionedProposal, error) {
+	// Although we re-submit proposal preparation on client restart,
+	// the spec doesn't guarantee it will be used:
+	//
+	// https://ethereum.github.io/beacon-APIs/#/Validator/prepareBeaconProposer
+	// > Note that there is no guarantee that the beacon node will
+	// > use the supplied fee recipient when creating a block proposal,
+	// > so on receipt of a proposed block the validator should confirm
+	// > that it finds the fee recipient within the block acceptable before signing it.
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: I mentioned this in [another comment](https://github.com/ssvlabs/ssv/pull/2415#discussion_r2244991596), but it probably got buried under other ones,

this comment-part should probably be in `getSingleClientProposal` ? Because here in `selectBestProposal` (or in multi-client flow in general) we don't even do anything preparation-related

File: beacon/goclient/proposer.go (hunk 16 above)
Comment (iurii-ssv) [reply beacon/goclient/proposer.go]: So, just for historical records, it looks like you've set it to `3.3s` now, right @nkryuchkov ? By using round 2 here:
```go
feeRecipientDeadline := gc.latestProposalTime(slot, 2)
```

File: beacon/goclient/proposer.go [hunk 29]
```diff
@@ -319,7 +225,651 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+	default:
+		gc.log.Error("❗️couldn't submit any proposal preparations",
+			zap.Int("total", len(preparations)),
+		)
+	}
+}
+
+// getProposal fetches proposals from beacon nodes and
+// returns the first received one with a fee recipient set,
+// or, if none, it returns the first received proposal.
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: Nit: `it returns the first received proposal.` -> `it returns the freshest received proposal.`

This behavior has changed with the latest updates. I think it doesn't really matter which proposal we take (if it has no fee recipient), just want the comment to be accurate.

File: beacon/goclient/proposer.go [hunk 30]
```diff
@@ -319,7 +225,651 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+	for {
+		select {
+		case p, ok := <-proposalCh:
+			if !ok {
+				// All request goroutines have finished, but we didn't get any proposal with fee recipient.
+
+				if fallbackProposal == nil {
+					// We don't have any proposals at all, so we got some error.
+					// The errors have been logged, so we don't need to return them.
+					return nil, fmt.Errorf("all requests failed")
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: `all requests failed` -> `none of proposal-fetch requests succeeded`

File: beacon/goclient/proposer.go [hunk 31]
```diff
@@ -319,7 +225,651 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+				}
+
+				// If we have a proposal without a fee recipient, it's better that nothing, so we use it.
+				gc.log.Warn("no proposals with fee recipient found")
+				return fallbackProposal, nil
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: `no proposals with fee recipient found` -> `all proposal-fetch requests finished but no proposals with fee recipient found, using proposal without fee recipient`

File: beacon/goclient/proposer.go [hunk 32]
```diff
@@ -319,7 +225,651 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+			hasFR, err := hasFeeRecipient(p)
+			if err != nil {
+				// If we cannot check fee recipient, either the block is malformed
+				// or hasFeeRecipient doesn't count all cases.
+				// So we just log it and consider the block as being without a fee recipient.
+				gc.log.Error("failed to check fee recipient", zap.Error(err))
+			}
+			if err != nil || !hasFR {
+				if feeRecipientCtx.Err() != nil {
+					gc.log.Debug("didn't receive proposal with fee recipient within the safe duration for the best round, accepting any proposal")
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: Nit: I think we should be more concrete with logs whenever possible (more details is better),

`didn't receive proposal with fee recipient within the safe duration for the best round, accepting any proposal` -> `didn't receive proposal with fee recipient in time for round 1, will use the proposal without fee recipient we got instead`

File: beacon/goclient/proposer.go [hunk 33]
```diff
@@ -319,7 +225,651 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+	// a proposal we are looking for, but it would increase the probability
+	// of being late with the proposal submission.
+	feeRecipientCtx, feeRecipientCancel := context.WithDeadline(ctx, gc.latestProposalTime(slot, 1))
+	defer feeRecipientCancel()
+
+	var fallbackProposal *api.VersionedProposal
+
+	// Wrapped with a for loop to enter the select again on feeRecipientCtx expiration.
+	for {
+		select {
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: So, now that we've simplified the way we are handling the cases in this `select` we also can get rid of `for` loop if we use `else` clause like this:
```go
			if err != nil || !hasFR {
				if feeRecipientCtx.Err() != nil {
					gc.log.Debug("didn't receive proposal with fee recipient within the safe duration for the best round, accepting any proposal")
					return p, nil
				}

				fallbackProposal = p
			} else {
                                 // Got a proposal with fee recipient. It is good enough, we can use it.
    			        gc.log.Debug("received a proposal with fee recipient")
			        return p, nil
			}
```

File: beacon/goclient/proposer.go [hunk 34]
```diff
@@ -319,7 +225,651 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+	if err != nil {
+		logger.Error("failed to submit a preparation and get a new proposal",
+			fields.Took(time.Since(newProposalStart)),
+			zap.Error(err))
+		return p.Data, nil
+	}
+
+	logger.Info("received a new proposal with fee recipient",
+		fields.Took(time.Since(newProposalStart)),
+		fields.Address(mustGetFeeRecipient(feeRecipientProposal).String()))
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: I think we could return `feeRecipient` directly from `submitPreparationsAndGetProposal` func to re-use it here, to:
- to avoid spending time on parsing the proposal object all over again just to log it
- get rid of `mustGetFeeRecipient` func (since it panics I'm a bit afraid it might be miss-used in the future)

File: beacon/goclient/proposer.go (hunk 28 above)
Comment (nkryuchkov) [reply beacon/goclient/proposer.go]: I meant proposal preparations that are submitted on client restart — they don't guarantee use by the client, therefore, we need this logic with the best proposal choice. Let me know if it doesn't sound clear, I'll rewrite it then

File: beacon/goclient/proposer.go (hunk 16 above)
Comment (nkryuchkov) [reply beacon/goclient/proposer.go]: @iurii-ssv no, I keep the round 1 here:
```go
feeRecipientCtx, feeRecipientCancel := context.WithDeadline(ctx, gc.latestProposalTime(slot, 1))
```
I set it to 3.3s for the single client, though

File: beacon/goclient/proposer.go (hunk 29 above)
Comment (nkryuchkov) [reply beacon/goclient/proposer.go]: Yeah, it forgot to update it, thanks. I'd use `last received proposal` though

File: beacon/goclient/proposer.go (hunk 33 above)
Comment (nkryuchkov) [reply beacon/goclient/proposer.go]: But after `fallbackProposal = p` we need to enter the select again

File: beacon/goclient/proposer.go (hunk 34 above)
Comment (nkryuchkov) [reply beacon/goclient/proposer.go]: Actually, I think I'd rather delete this field as well as `mustGetFeeRecipient`, anyway, we'll log it later in `ProcessPreConsensus` again

File: beacon/goclient/proposer.go (hunk 16 above)
Comment (iurii-ssv) [reply beacon/goclient/proposer.go]: Yeah yeah, I'm talking about single-client case here. For multi-client it is at 1.3s (as it should be).

File: beacon/goclient/proposer.go (hunk 33 above)
Comment (iurii-ssv) [reply beacon/goclient/proposer.go]: > But after `fallbackProposal = p` we need to enter the select again

Oh, you are right, I missed that, then I guess we are stuck with `for` loop :)

File: beacon/goclient/proposer.go (hunk 16 above)
Comment (nkryuchkov) [reply beacon/goclient/proposer.go]: yes, 
single client 3.3s
multi client 1.3s

File: beacon/goclient/proposer.go (hunk 28 above)
Comment (iurii-ssv) [reply beacon/goclient/proposer.go]: Ah, hmm, I thought you are referring to a different scenario that's **applicable only to single-client case** which is: "even though we send proposal-preparation for single client if necessary, there is no guarantee that preparation will be applied in time - **before** we request the next block". I guess it's not something we should have a comment about (because it's non-actionable, and depends on specific Beacon node implementation), I just thought that's what this comment is trying to say:
```go
	// Although we re-submit proposal preparation on client restart,
	// the spec doesn't guarantee it will be used:
	//
	// https://ethereum.github.io/beacon-APIs/#/Validator/prepareBeaconProposer
	// > Note that there is no guarantee that the beacon node will
	// > use the supplied fee recipient when creating a block proposal,
	// > so on receipt of a proposed block the validator should confirm
	// > that it finds the fee recipient within the block acceptable before signing it.
```
^ this comment however applies to both single and multi client cases, so I think it makes sense to have it on top of `getProposal` func instead (also because it mentions the fee-recipient stuff already) - this would be my only suggestion here.

**Review by iurii-ssv — APPROVED** [review]

File: beacon/goclient/proposer.go [hunk 35]
```diff
@@ -319,7 +225,635 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+	return gc.getMultiClientProposal(ctx, slot, sig, graffiti)
+}
+
+func (gc *GoClient) getSingleClientProposal(
+	ctx context.Context,
+	slot phase0.Slot,
+	sig phase0.BLSSignature,
+	graffiti [32]byte,
+) (*api.VersionedProposal, error) {
+	logger := gc.log.With(fields.Address(gc.clients[0].Address()))
```
Comment (oleg-ssvlabs) [inline beacon/goclient/proposer.go]: nit: `gc.clients[0] `is called 3 times in this method, maybe worth declaring a var for it?

```Go
client := gc.clients[0]
```

File: beacon/goclient/proposer.go [hunk 36]
```diff
@@ -319,7 +225,635 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+
+	proposalPreparation := []*eth2apiv1.ProposalPreparation{
+		{
+			ValidatorIndex: validatorIndex,
+			FeeRecipient:   address,
+		},
+	}
+
+	preparationsReqStart := time.Now()
+	err := gc.clients[0].SubmitProposalPreparations(ctx, proposalPreparation)
```
Comment (oleg-ssvlabs) [inline beacon/goclient/proposer.go]: nit: same here regarding `gc.clients[0]`

File: beacon/goclient/proposer.go [hunk 37]
```diff
@@ -319,7 +225,635 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+
+			hasFR, err := hasFeeRecipient(p)
+			if err != nil {
+				// If we cannot check fee recipient, either the block is malformed
+				// or hasFeeRecipient doesn't count all cases.
+				// So we just log it and consider the block as being without a fee recipient.
+				gc.log.Error("failed to check fee recipient", zap.Error(err))
+			}
+			if err != nil || !hasFR {
+				if feeRecipientCtx.Err() != nil {
```
Comment (oleg-ssvlabs) [inline beacon/goclient/proposer.go]: Isn't it better to listen to the `feeRecipientCtx.Done()` channel in the `select` statement,  
instead of checking for an error here like this? (Same as we do with `ctx.Done()` a few lines below.)

File: beacon/goclient/proposer.go [hunk 38]
```diff
@@ -319,7 +225,635 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+
+	go func() {
+		wg.Wait()
+		close(proposalCh)
+	}()
+
+	return proposalCh
+}
+
+func (gc *GoClient) selectBestProposal(
```
Comment (oleg-ssvlabs) [inline beacon/goclient/proposer.go]: May I ask why it is called the "Best" proposal?  
I don’t think there is any logic for determining that - it just listens to all proposals and returns the latest one that arrived, right? 
Or is the latest one actually considered the best?

**Review by oleg-ssvlabs — COMMENTED** [review]
Great job!

Just left couple of minor comments

File: beacon/goclient/proposer.go (hunk 38 above)
Comment (iurii-ssv) [reply beacon/goclient/proposer.go]: The best one is the one that has fee-recipient (some might not have it)

File: beacon/goclient/proposer.go (hunk 37 above)
Comment (iurii-ssv) [reply beacon/goclient/proposer.go]: That would probably mean we'd need to "rewrite a bit" the way these channels are handled (maybe similar to how I suggested to do it [here](https://github.com/ssvlabs/ssv/pull/2415#discussion_r2249185032))

I like my implementation better (obviously, lol) purely from readability perspective, but I wouldn't say one is better than another in terms of actual code execution.

File: beacon/goclient/proposer.go [hunk 39]
```diff
@@ -319,7 +225,635 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+	if err != nil {
+		logger.Error("failed to submit a preparation and get a new proposal",
+			fields.Took(time.Since(newProposalStart)),
+			zap.Error(err))
+		return p.Data, nil
+	}
+
+	logger.Info("received a new proposal with fee recipient", fields.Took(time.Since(newProposalStart)))
+
+	return feeRecipientProposal, nil
```
Comment (olegshmuelov) [inline beacon/goclient/proposer.go]: The current implementation doesn't differentiate between blinded and regular blocks when handling missing fee recipients.

For blinded (MEV) blocks:
- Fee recipient is set based on validator registrations
- Submitting proposal preparations won't fix missing fee recipients
- The current "fix" attempts are ineffective and cause unnecessary delays

Same issue exists in `selectBestProposal` for multi-client scenarios.

Comment (iurii-ssv) [reply beacon/goclient/proposer.go]: I think this PR wasn't meant to (and I don't think we really can) address the missing fee-recipient in case of MEV-block,

do you think we should request non-MEV block (also maybe doing prior pre-proposal request ?) in case we got blinded(MEV) block without fee-recipient ? It's probably too late to do it anyway since MEV-block-producers might also additionally/intentionally delay their response(s) to the latest point possible to extract more MEV.

But to be clear, I also don't particularly like that in this PR we are adding some code that works differently depending on whether we are running in **single-client** mode or **multi-client** mode. But, using **multi-client** instead of **single-client** mode is an indirect solution for "potential zero fee recipient issue" (and that's why we only handle/send proposal-preparation explicitly for single-client case only).

Regardless of what we decide to do with "potential zero fee recipient issue", I do think however that we'll want to adopt the parallel block-fetch @nkryuchkov implemented in this PR (for **multi-client** mode) if not to address "potential zero fee recipient issue" then just to speed up proposer-duty and make it more stable to 1-CL failures.

File: beacon/goclient/proposer.go [hunk 40]
```diff
@@ -319,7 +225,635 @@ func (gc *GoClient) SubmitProposalPreparation(
 		})
 	}
 
-	return gc.multiClientSubmit(ctx, "SubmitProposalPreparations", func(ctx context.Context, client Client) error {
-		return client.SubmitProposalPreparations(ctx, preparations)
+	gc.submitProposalPreparationBatches(ctx, preparations)
+	gc.feeRecipientsCache.Store(&feeRecipients)
```
Comment (olegshmuelov) [inline beacon/goclient/proposer.go]: `feeRecipientsCache` is only updated during periodic submissions (every epoch/2), not when fee recipient update events occur.

Timeline of the bug:
1. Fee recipient update event processed → validator share updated in memory
2. Cache remains stale with old fee recipient
3. If CL restarts before next periodic submission → old fee recipient re-submitted
4. Window of vulnerability: up to half an epoch (~3.2 minutes)

File: beacon/goclient/proposer.go
Comment (olegshmuelov) [inline beacon/goclient/proposer.go:1]: This PR adds critical block proposal logic but has only 15% test coverage. Given the complexity of the multi-client proposal selection and fee recipient validation logic, comprehensive tests are essential. We should consider adding:
- Unit tests for `hasFeeRecipient` and `getFeeRecipient`
- Tests for `selectBestProposal` with various scenarios (timeout, no fee recipient, mixed results)

File: beacon/goclient/goclient.go [hunk 41]
```diff
@@ -377,6 +381,12 @@ func (gc *GoClient) singleClientHooks() *eth2clienthttp.Hooks {
 				zap.Uint64("data_version", uint64(dataVersion)),
 				zap.Stringer("config", currentConfig),
 			)
+
+			if feeRecipients := gc.feeRecipientsCache.Load(); feeRecipients != nil {
+				if err := gc.SubmitProposalPreparation(ctx, *feeRecipients); err != nil {
+					logger.Error("failed to submit proposal preparations after client restart", zap.Error(err))
+				}
```
Comment (olegshmuelov) [inline beacon/goclient/goclient.go]: The `OnActive` hook submits to all clients when only one reconnects.

Current behavior:
1. Single CL node reconnects → triggers `OnActive` hook
2. Calls `gc.SubmitProposalPreparation()`
3. This uses `multiClientSubmit()` → submits to ALL clients
4. Result: Unnecessary duplicate submissions to already-connected clients

File: beacon/goclient/proposer.go [hunk 42]
```diff
@@ -319,7 +225,635 @@ func (gc *GoClient) SubmitProposalPreparation(
...
+		return nil, err
+	}
+
+	ok, err := hasFeeRecipient(p.Data)
+	if err != nil {
+		// If we cannot check fee recipient, either the block is malformed
+		// or hasFeeRecipient doesn't count all cases.
+		// So we just log it, return the block we received,
+		// and let the caller decide what to do with it.
+		logger.Error("failed to check fee recipient", zap.Error(err))
```
Comment (olegshmuelov) [inline beacon/goclient/proposer.go]: Standardize logging levels based on whether execution continues or stops:

Current (incorrect):
- Line 250: gc.log.Error("could not submit proposal preparation batch") → continues
- Line 339: logger.Error("failed to check fee recipient") → returns block anyway
- Line 371: logger.Error("failed to extract validator index") → returns block anyway
- Line 380: logger.Error("failed to submit preparation and get new proposal") → returns block anyway
- Line 537: gc.log.Error("failed to check fee recipient") → continues processing

Suggested fix - change to Warn for all cases that continue:
```go
// Line 250
gc.log.Warn("could not submit proposal preparation batch",
    zap.Int("start_index", start),
    zap.Error(err))

// Line 339
logger.Warn("failed to check fee recipient, continuing with block",
    zap.Error(err))

// Line 371
logger.Warn("failed to extract validator index, continuing with original block",
    zap.Error(err))

// Line 380
logger.Warn("failed to submit preparation and get new proposal, using original",
    fields.Took(time.Since(newProposalStart)),
    zap.Error(err))

// Line 537
gc.log.Warn("failed to check fee recipient, treating as missing",
    zap.Error(err))
```

Reserve Error level for cases that actually stop processing or return errors.

**Review by olegshmuelov — CHANGES_REQUESTED** [review]
Gaps from Issue #2408 Not Addressed
 
 also
 https://github.com/ssvlabs/ssv/issues/2408#issuecomment-3174809247

File: beacon/goclient/proposer.go (hunk 39 above)
Comment (olegshmuelov) [reply beacon/goclient/proposer.go]: I'm not asking to solve MEV fee recipient issues. I'm asking to stop trying to fix them with the wrong method (proposal preparations) which just wastes time and won't work anyway.

Comment (iurii-ssv) [reply beacon/goclient/proposer.go]: I don't disagree with that. Just providing some context for why this PR looks the way it does currently (since I was requesting quite a bit of changes to it myself).

**Comment by olegshmuelov** [comment]
**Why the Simplified Approach**

  The original solution attempted to handle nil fee recipients reactively:
  1. Submit proposal preparations → Get nil fee recipient error → Re-submit preparations → Re-request block

  This approach had issues:
  - Uncertain effectiveness: The block is cached in the beacon node and also requests data from the execution layer, so it's unclear if you'll get a block with updated fee recipient quickly enough - and we can't afford to wait
  - Adds latency to consensus: While QBFT supports round changes, adding retry loops for fee recipient fixes delays the initial proposal, potentially causing unnecessary round changes
  - Complex retry logic that's hard to test and debug

  **The New Approach**

  We simplified the implementation by removing the reactive retry mechanism:
  - We don't re-submit proposal preparations directly when fee recipient is nil
  - Instead, we re-submit preparations proactively on specific events:
    - Beacon node restart/reconnect
    - Fee recipient update event
    - New validators starting
    - Validators becoming active in the next epoch (preparation for upcoming duties)
  - When using multiple beacon clients, we race them to get the first proposal response as fast as possible to start the QBFT consensus quickly.
  
  **Bottom line: Better to propose with nil fee recipient than lose the entire block.**

File: beacon/goclient/proposer.go [hunk 43]
```diff
@@ -176,6 +201,77 @@ func (gc *GoClient) GetBeaconBlock(
...
+		case <-ctx.Done():
+			return nil, ctx.Err()
+		}
+	}
+
+	// All clients failed
+	if lastErr != nil {
+		return nil, fmt.Errorf("all %d clients failed to get proposal for slot %d: %w", len(gc.clients), slot, lastErr)
+	}
+	return nil, fmt.Errorf("all %d clients failed to get proposal for slot %d", len(gc.clients), slot)
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: Nit: if I'm reading this code correctly `lastErr` can't ever be `nil` here, so maybe we can simplify it down to:
```go
return nil, fmt.Errorf("all %d clients failed to get proposal for slot %d: %w", len(gc.clients), slot, lastErr)
```

File: beacon/goclient/proposer.go [hunk 44]
```diff
@@ -307,19 +403,89 @@ func (gc *GoClient) SubmitBeaconBlock(
...
+				zap.String("api", "SubmitProposalPreparations"),
+				zap.Int("batch_start", start),
+				zap.Int("batch_size", len(batch)),
+				zap.Error(err),
+			)
+			lastErr = err
+			continue
+		}
+		submitted += len(batch)
+	}
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: Maybe this chunking-code can be simplified with `slices.Chunk` (similar to how we are doing it here - https://github.com/ssvlabs/ssv/blob/e2eb0177533617c2aff5de11e0269d84325a77fa/beacon/goclient/validator.go#L49-L59) ? But probably not worth rewriting this for.

File: beacon/goclient/proposer.go [hunk 45]
```diff
@@ -307,19 +403,89 @@ func (gc *GoClient) SubmitBeaconBlock(
...
+		)
+		return nil
+
+	case submitted > 0:
+		gc.log.Error("partially submitted proposal preparations",
+			zap.Int("submitted", submitted),
+			zap.Int("errored", len(preparations)-submitted),
+			zap.Int("total", len(preparations)),
+		)
+		return fmt.Errorf("partially submitted preparations: %d/%d, last error: %w", submitted, len(preparations), lastErr)
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: We probably want to log `lastErr` (with `gc.log.Error`) as well ... otherwise the log line is "incomplete" ...

File: beacon/goclient/proposer.go [hunk 46]
```diff
@@ -307,19 +403,89 @@ func (gc *GoClient) SubmitBeaconBlock(
...
+
+	default:
+		gc.log.Error("couldn't submit any proposal preparations",
+			zap.Int("total", len(preparations)),
+		)
+		return fmt.Errorf("failed to submit any preparations: %w", lastErr)
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: ditto about logging `lastErr`

File: operator/node.go [hunk 47]
```diff
@@ -92,20 +104,20 @@ func New(logger *zap.Logger, opts Options, exporterOpts exporter.Options, slotTi
...
 		wsAPIPort: opts.WsAPIPort,
 	}
 
+	// Wire the beacon client to the fee recipient controller
+	// This allows the beacon client to pull proposal preparations on reconnect
+	opts.BeaconNode.SetProposalPreparationsProvider(feeRecipientCtrl.GetProposalPreparations)
+
+	// Wire the validator controller to fee recipient controller
+	// This allows fee recipient controller to be notified when fee recipient changes occur
+	opts.ValidatorController.SetFeeRecipientChangeChan(feeRecipientCtrl.FeeRecipientChangeChan())
```
Comment (iurii-ssv) [inline operator/node.go]: I'd prefer if we could just use constructor (instead of setters) to keep the initialization order straightforward, but I assume that would require quite a bit of refactoring, right ? Anyway, not really relevant to this PR but I suspect we might need to untangle that in the future ...

File: operator/validator/controller.go [hunk 48]
```diff
@@ -1007,10 +1013,13 @@ func (c *controller) handleMetadataUpdate(ctx context.Context, syncBatch metadat
...
 			c.logger.Debug("started new eligible validators", zap.Int("started_validators", startedValidators))
 
-			// Refresh duties only if there are started validators.
+			// Refresh duties and fee recipients only if there are started validators.
 			if !c.reportIndicesChange(ctx) {
 				c.logger.Error("failed to notify indices change")
 			}
+			if !c.reportFeeRecipientChange(ctx) {
+				c.logger.Error("failed to notify fee recipient change")
+			}
```
Comment (iurii-ssv) [inline operator/validator/controller.go]: Perhaps we'd want to add some description for why we are calling `reportFeeRecipientChange` (and maybe `reportIndicesChange` could use a bit of a comment as well, it's currently non-trivial to figure out what it does) here because it might not be obvious why this is needed,

I guess applies to all the places where it might not be obvious (eg. Beacon node restart/reconnect)

File: operator/fee_recipient/controller.go [hunk 49]
```diff
@@ -19,121 +18,141 @@ import (
...
+func (rc *recipientController) listenToFeeRecipientChanges(ctx context.Context) {
+	for {
+		select {
+		case <-ctx.Done():
+			return
+		case <-rc.feeRecipientChangeCh:
+			rc.logger.Debug("fee recipient change detected, submitting proposal preparations")
+			if err := rc.prepareAndSubmit(ctx); err != nil {
+				rc.logger.Warn("could not submit proposal preparations after fee recipient change", zap.Error(err))
+			}
```
Comment (iurii-ssv) [inline operator/fee_recipient/controller.go:136]: We might get a lot of individual submissions on `rc.feeRecipientChangeCh` channel due to `UpdateFeeRecipient` events (if somebody updates fee-recipient for his 100 or 1000 validators, all at once) ? Which will result in the same amount of requests to Beacon node. If that's the case we'd probably want to buffer these submissions similar to how [we buffer validator-registrations submissions](https://github.com/ssvlabs/ssv/blob/e2eb0177533617c2aff5de11e0269d84325a77fa/protocol/v2/ssv/runner/validator_registration.go#L471-L489) ...

File: operator/validator/task_executor.go [hunk 50]
```diff
@@ -107,6 +112,14 @@ func (c *controller) UpdateFeeRecipient(owner, recipient common.Address, blockNu
 		return true
 	})
 
+	if updated {
+		go func() {
+			if !c.reportFeeRecipientChange(c.ctx) {
+				logger.Error("failed to notify fee recipient change")
+			}
+		}()
+	}
```
Comment (iurii-ssv) [inline operator/validator/task_executor.go]: Nit: we could inline this `go func() ...` instead of defining additional variable `update`

File: operator/validator/controller.go [hunk 51]
```diff
@@ -1031,6 +1040,23 @@ func (c *controller) reportIndicesChange(ctx context.Context) bool {
 	}
 }
 
+func (c *controller) reportFeeRecipientChange(ctx context.Context) bool {
+	if c.feeRecipientChangeCh == nil {
+		c.logger.Error("fee recipient change channel not configured")
+		return false
+	}
```
Comment (iurii-ssv) [inline operator/validator/controller.go]: Is this even possible for `feeRecipientChangeCh` to be `nil` ? I think this can only happen if we wired our code incorrectly ... so I would rather let it panic if that's the case - so we can easily discover that (rather than potentially missing this error in logs)

File: beacon/goclient/proposer.go [hunk 52]
```diff
@@ -307,19 +403,89 @@ func (gc *GoClient) SubmitBeaconBlock(
...
 		})
+	})
+}
+
+// handleProposalPreparationsOnReconnect re-submits proposal preparations when a beacon client reconnects
+// This helps beacon nodes that lost preparations on restart
+func (gc *GoClient) handleProposalPreparationsOnReconnect(ctx context.Context, client Client, logger *zap.Logger) {
+	if gc.proposalPreparationsProvider == nil {
+		logger.Debug("proposal preparations provider not set, skipping re-submission")
+		return
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: > Is this even possible for `feeRecipientChangeCh` to be `nil` ? I think this can only happen if we wired our code incorrectly ... so I would rather let it panic if that's the case - so we can easily discover that (rather than potentially missing this error in logs)

Same here ^ I guess

File: beacon/goclient/proposer.go [hunk 53]
```diff
@@ -176,6 +201,77 @@ func (gc *GoClient) GetBeaconBlock(
 	}
 }
 
+// getProposalParallel fetches proposals from all beacon nodes in parallel
+// and returns the first successful response. This approach minimizes latency
+// by racing multiple clients, which is important for block proposals where
+// timing is critical. The function cancels remaining requests as soon as
+// the first successful response is received to avoid unnecessary load.
+func (gc *GoClient) getProposalParallel(
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: Another improvement (at the cost of code complexity) Nikita previously had this **func** to do is to try and prioritize a proposal that has fee recipient on it IF we got several proposals before some "soft deadline",

not sure if we need this feature or not, but maybe we want expand the comment on this func to state that "we don't do that because it results in higher delay that might potentially result in missed proposal"

**Review by iurii-ssv — COMMENTED** [review]
Super helpful summary (old vs new)! Just minor suggestions from me.

File: beacon/goclient/goclient.go [hunk 54]
```diff
@@ -173,8 +175,8 @@ type GoClient struct {
 	// since it doesn't change over time
 	voluntaryExitDomainCached atomic.Pointer[phase0.Domain]
 
-	// feeRecipientsCache is used to re-submit proposal preparations on Beacon node restart.
-	feeRecipientsCache atomic.Pointer[map[phase0.ValidatorIndex]bellatrix.ExecutionAddress]
+	// proposalPreparationsProvider is a callback to get current proposal preparations from the fee recipient controller
+	proposalPreparationsProvider func() ([]*eth2apiv1.ProposalPreparation, error)
```
Comment (nkryuchkov) [inline beacon/goclient/goclient.go]: Interfaces are usually encouraged to be used over callbacks in Go. We can just pass `feeRecipientCtrl` instead of `feeRecipientCtrl.GetProposalPreparations`

File: beacon/goclient/proposer.go [hunk 55]
```diff
@@ -64,22 +88,188 @@ func (gc *GoClient) GetBeaconBlock(
...
+					// Context canceled, exit without blocking
+				}
+				return
+			}
+
+			select {
+			case resultCh <- result{proposal: proposal, address: c.Address()}:
+			case <-parallelCtx.Done():
+				// Context canceled, exit without blocking
+			}
```
Comment (nkryuchkov) [inline beacon/goclient/proposer.go]: Do we need to check the error? We can use just one `select` and pass directly what `gc.fetchProposal` returned

File: beacon/goclient/proposer_test.go [hunk 56]
```diff
@@ -2,265 +2,718 @@ package goclient
...
+		if resp, ok := beaconEndpointResponses[r.URL.Path]; ok {
+			w.Header().Set("Content-Type", "application/json")
+			if _, err := w.Write(resp); err != nil {
+				w.WriteHeader(http.StatusInternalServerError)
+			}
+			return
+		}
+
+		// Handle proposal endpoint
+		if strings.HasPrefix(r.URL.Path, "/eth/v3/validator/blocks/") {
```
Comment (nkryuchkov) [inline beacon/goclient/proposer_test.go]: It's inconsistent with `proposalPreparationEndpoint`: one is a const, another one isn't

File: beacon/goclient/goclient.go (hunk 54 above)
Comment (iurii-ssv) [reply beacon/goclient/goclient.go]: Is there any real benefit to using 1-method interface over `func` here ? 
- I guess IDE will let us find the implementation in 1-click (vs this won't be the case for func)
- but for a single-method case I would personally prefer `func` over defining yet another `interface` (all else being equal)

still, this is probably opinionated stuff we can't make uniform across the whole repo anyway

File: operator/node.go (hunk 47 above)
Comment (olegshmuelov) [reply operator/node.go]: I investigated replacing the setters with constructor-based DI, but there's a circular dependency that makes this challenging:

  - `BeaconNode` needs `FeeRecipientController.GetProposalPreparations()`
  - `FeeRecipientController` needs `BeaconNode` in its constructor

  While we could work around this with lazy initialization or proxy objects, it would add complexity without clear benefit. The current setter approach cleanly breaks this circular dependency and keeps the initialization straightforward.

  As you noted, this would indeed require significant refactoring. I'll keep the current approach for this PR.

File: operator/fee_recipient/controller.go (hunk 49 above)
Comment (olegshmuelov) [reply operator/fee_recipient/controller.go:136]: You're right to consider batching, but let me clarify the actual behavior: When `UpdateFeeRecipient` is called for an owner with many validators, it updates ALL validators for that owner and sends only one notification to `feeRecipientChangeCh` (not one per validator).

  The scenarios where we might see multiple submissions in quick succession are:
  1. Multiple different owners updating fee recipients
  2. New validators being added + reactivation + fee recipient updates happening close together
  3. These events coinciding with the periodic epoch submission

  Currently, the channel buffer of 1 provides natural coalescing for rapid events, and the beacon client already batches internally (500 preparations per request).

  While we could implement a batching mechanism similar to validator registrations (with a 2-3 second delay), the current implementation should be sufficient given that:
  - These events are relatively infrequent
  - Even in worst case, we're talking about a few submissions, not hundreds
  - The beacon node can handle these requests without issue

File: operator/validator/task_executor.go (hunk 50 above)
Comment (olegshmuelov) [reply operator/validator/task_executor.go]: > Nit: we could inline this `go func() ...` instead of defining additional variable `update`

  I'm not sure I understand the suggestion. The `updated` variable is needed to:
  - Track if any validators were actually updated
  - Ensure we send only ONE notification after updating ALL validators for the owner

  Without it, how would we know whether to send the notification? Could you clarify what you mean by "inline this go func"?

File: beacon/goclient/goclient.go (hunk 54 above)
Comment (olegshmuelov) [reply beacon/goclient/goclient.go]: Thanks for the feedback! I'm keeping the function callback approach here because:
  1. It's simpler for a single method that's unlikely to grow
  2. It follows patterns used in the Go standard library (like `http.HandlerFunc`)
  3. The function approach is working well for this specific use case where we just need to fetch preparations

  As @iurii-ssv noted, this is somewhat opinionated and both approaches are valid in Go.

File: beacon/goclient/proposer.go (hunk 55 above)
Comment (olegshmuelov) [reply beacon/goclient/proposer.go]: Good catch! Simplified to use a single `select` statement regardless of error. Much cleaner, thanks!
5d4365be27af97215ec03e36269e1a10b994b331

File: beacon/goclient/proposer.go (hunk 43 above)
Comment (olegshmuelov) [reply beacon/goclient/proposer.go]: https://github.com/ssvlabs/ssv/pull/2415/commits/398946a07dd3f0d6f671b7b390a1b00c84f849f2

File: beacon/goclient/proposer.go (hunk 44 above)
Comment (olegshmuelov) [reply beacon/goclient/proposer.go]: https://github.com/ssvlabs/ssv/pull/2415/commits/3f1c0b7b1cd82a861cf9248cc81aecc6e6965042

File: beacon/goclient/proposer.go (hunk 45 above)
Comment (olegshmuelov) [reply beacon/goclient/proposer.go]: https://github.com/ssvlabs/ssv/commit/398946a07dd3f0d6f671b7b390a1b00c84f849f2

File: beacon/goclient/proposer.go (hunk 46 above)
Comment (olegshmuelov) [reply beacon/goclient/proposer.go]: https://github.com/ssvlabs/ssv/commit/398946a07dd3f0d6f671b7b390a1b00c84f849f2

File: operator/validator/controller.go (hunk 48 above)
Comment (olegshmuelov) [reply operator/validator/controller.go]: https://github.com/ssvlabs/ssv/pull/2415/commits/5171fc4543d5eeadf1a42c672de84121760c1036

File: operator/validator/controller.go (hunk 51 above)
Comment (olegshmuelov) [reply operator/validator/controller.go]: https://github.com/ssvlabs/ssv/pull/2415/commits/f9d87d2b9270100a57d32f77d8baf5ee24c02b3d

File: beacon/goclient/proposer.go (hunk 52 above)
Comment (olegshmuelov) [reply beacon/goclient/proposer.go]: This nil check is intentionally kept, but for a different reason than defensive programming.

  The `proposalPreparationsProvider` is nil on initial connection and only gets set later via `SetProposalPreparationsProvider`.  Since the `OnActive` hook fires for both initial connections and reconnections (for each client in a multi-client setup), we use this nil check to distinguish between them:
  - Initial connection: provider is nil -> skip (applies to all clients during startup)
  - Reconnection: provider is set -> re-submit preparations (for any client that reconnects later)

  This is different from the `feeRecipientChangeCh` case where the channel should never be nil during normal operation. Here, the provider being nil is an expected state during initialization.

  I've added comments to clarify this is intentional behavior, not defensive programming.
  https://github.com/ssvlabs/ssv/pull/2415/commits/beb897e340a47ea5705638df79a33d8e8228cc89

File: beacon/goclient/proposer.go (hunk 53 above)
Comment (olegshmuelov) [reply beacon/goclient/proposer.go]: https://github.com/ssvlabs/ssv/pull/2415/commits/45acfeef0f13621ce97fd2cbf43130b9fabcb636

File: beacon/goclient/proposer_test.go (hunk 56 above)
Comment (olegshmuelov) [reply beacon/goclient/proposer_test.go]: 5d4365be27af97215ec03e36269e1a10b994b331

File: beacon/goclient/proposer.go (hunk 52 above)
Comment (olegshmuelov) [reply beacon/goclient/proposer.go]: **Update**: Implemented a better solution that addresses this concern properly. Now using an explicit `seenClients` map to track connection state, which reliably distinguishes initial connections from
  reconnections. The nil check only remains as a safety guard for the startup race condition (when reconnection might happen before `SetProposalPreparationsProvider` is called). This approach is more
  robust and doesn't rely on provider initialization order.
0d7d1fa92d744037e429dcaac93c54b04fbb1e23

File: operator/validator/task_executor.go (hunk 50 above)
Comment (iurii-ssv) [reply operator/validator/task_executor.go]: Ah yeah, I didn't consider that we only want to send **1 notification at the end** (so inlining this func - just moving it to where we do `updated = true`, and removing `updated` var), not a separate notification per validator updated

File: operator/fee_recipient/controller.go (hunk 49 above)
Comment (iurii-ssv) [reply operator/fee_recipient/controller.go:136]: > When UpdateFeeRecipient is called for an owner with many validators, it updates ALL validators for that owner and sends only one notification to feeRecipientChangeCh (not one per validator).

I [kind of missed that part](https://github.com/ssvlabs/ssv/pull/2415#discussion_r2297517084) ... I guess it's fine then since `UpdateFeeRecipientTask` is "1 per owner" (rather than "1 per validator" as I originally assumed)

So yeah, looking good as is currently implemented.

File: operator/node.go (hunk 47 above)
Comment (iurii-ssv) [reply operator/node.go]: Yes, I agree it's better to refactor this separately from this PR anyway, and since we want to release this PR asap it's better to do after (not before)

File: beacon/goclient/proposer.go [hunk 57]
```diff
@@ -307,19 +393,92 @@ func (gc *GoClient) SubmitBeaconBlock(
...
+func (gc *GoClient) handleProposalPreparationsOnReconnect(ctx context.Context, client Client, logger *zap.Logger) {
+	gc.proposalPreparationsProviderMu.RLock()
+	provider := gc.proposalPreparationsProvider
+	gc.proposalPreparationsProviderMu.RUnlock()
+
+	// Provider might be nil if reconnection happens during startup before SetProposalPreparationsProvider is called
+	if provider == nil {
+		logger.Warn("proposal preparations provider not set yet, skipping re-submission on reconnect")
+		return
 	}
```
Comment (iurii-ssv) [inline beacon/goclient/proposer.go]: From what I understand we shouldn't ever hit this `Warn` assuming we wired our code correctly ? If that's indeed the case I would make it clear in the warn-message (or code-comment nearby) - so we'd know we need to fix something if we ever encounter this warning

**Review by iurii-ssv — APPROVED** [review]

**Review by iurii-ssv — APPROVED** [review]

File: operator/validator/controller.go [hunk 58]
```diff
@@ -115,6 +115,7 @@ type Controller interface {
 	IndicesChangeChan() chan struct{}
 	ValidatorRegistrationChan() <-chan duties.RegistrationDescriptor
 	ValidatorExitChan() <-chan duties.ExitDescriptor
+	SetFeeRecipientChangeChan(ch chan struct{})
```
Comment (oleg-ssvlabs) [inline operator/validator/controller.go]: nit: restrict this to be unidirectional channel (send)

File: operator/validator/controller.go [hunk 59]
```diff
@@ -194,6 +195,7 @@ type controller struct {
 	indicesChangeCh         chan struct{}
 	validatorRegistrationCh chan duties.RegistrationDescriptor
 	validatorExitCh         chan duties.ExitDescriptor
+	feeRecipientChangeCh    chan struct{}
```
Comment (oleg-ssvlabs) [inline operator/validator/controller.go:198]: this channel as well for sending only

File: operator/validator/controller.go [hunk 60]
```diff
@@ -304,6 +306,10 @@ func (c *controller) ValidatorExitChan() <-chan duties.ExitDescriptor {
 	return c.validatorExitCh
 }
 
+func (c *controller) SetFeeRecipientChangeChan(ch chan struct{}) {
```
Comment (oleg-ssvlabs) [inline operator/validator/controller.go]: I am not really sure I like this pattern.  

It is unclear to me who owns the channel. The owner of the channel should be the producer. In this case, the producer is the `ValidatorController`.  

In this implementation, however, the channel is instantiated in the `FeeRecipientController` and then passed to the `ValidatorController`. This means the data owner is the `ValidatorController`, but the owner of the channel is the `FeeRecipientController`.  

A setup I like more is for the `ValidatorController` to expose a method that returns a channel - essentially a `Subscribe` method that allows others to subscribe to fee recipient events. In this case, the `ValidatorController` owns the write channel, and the `FeeRecipientController` receives a read channel. The producer then decides the lifecycle of the channel (e.g., closing it).  `Subscribe()` method can support multiple subscribers (collection of channels it loops and publishes to) or single subscriber - in that case if Subscribe() called twice - it just returns already instantiated in the previous call channel.

File: operator/fee_recipient/controller.go [hunk 61]
```diff
@@ -19,121 +18,141 @@ import (
...
+		recipientStorage:     opts.RecipientStorage,
+		slotTickerProvider:   opts.SlotTickerProvider,
+		operatorDataStore:    opts.OperatorDataStore,
+		feeRecipientChangeCh: make(chan struct{}, 1),
 	}
 }
 
 func (rc *recipientController) Start(ctx context.Context) {
-	rc.listenToTicker(ctx)
+	go rc.listenToTicker(ctx)
```
Comment (oleg-ssvlabs) [inline operator/fee_recipient/controller.go]: I would rename this method so that it clearly indicates it submits proposal preparations.  
Maybe something like: `submitProposalsOnTick` or similar.

File: operator/node.go [hunk 62]
```diff
@@ -92,20 +104,20 @@ func New(logger *zap.Logger, opts Options, exporterOpts exporter.Options, slotTi
...
-		}),
+		feeRecipientCtrl: feeRecipientCtrl,
 
 		ws:        opts.WS,
 		wsAPIPort: opts.WsAPIPort,
 	}
 
+	// Wire the beacon client to the fee recipient controller
+	// This allows the beacon client to pull proposal preparations on reconnect
+	opts.BeaconNode.SetProposalPreparationsProvider(feeRecipientCtrl.GetProposalPreparations)
```
Comment (oleg-ssvlabs) [inline operator/node.go:115]: From what I understand, there is a circular dependency between `GoClient` and `FeeRecipientController`.  
It seems slightly problematic that `GetProposalPreparations` is passed to `GoClient` after its instantiation (and not in the constructor), because from what I see, `GoClient` requires a `proposal preparations provider` during the client activation `OnActive` hook.  

When does that hook run? Is there a chance that the `OnActive` hook is triggered with `isReconnection` set to `true` before the `proposal preparations provider` is passed?

Comment (olegshmuelov) [reply operator/node.go:115]: The `OnActive` hook runs when the beacon client establishes a connection.

Yes, there's a small window during startup where a reconnection could theoretically occur before the provider is set. This happens if the beacon client (created in `goclient.New()`) connects, disconnects, and reconnects before `operator.New()` completes and calls `SetProposalPreparationsProvider()`.

The `if provider == nil` check handles this gracefully:
  1. On initial connection (`isReconnection=false`), `handleProposalPreparationsOnReconnect` is never called
  2. If an early reconnection happens before the provider is set, we simply skip re-submission - this is harmless since there are no preparations to re-submit yet
  3. Once the fee recipient controller starts, regular scheduled submissions will handle everything

 The nil check ensures safe operation during the initialization sequence.
  
 slightly adjusted logging
 75ec2e98f98b4d44d054f5dfa3f664dcf3379509

File: operator/validator/controller.go (hunk 60 above)
Comment (olegshmuelov) [reply operator/validator/controller.go]: Thanks for the suggestion!
Looks better now
e3aba4cebea6fc4db4b56b71217cecd1b673770e

File: operator/fee_recipient/controller.go (hunk 61 above)
Comment (olegshmuelov) [reply operator/fee_recipient/controller.go]: f659c4177bf5e1411cad137ae55257a7761dfb62

File: operator/node.go (hunk 47 above)
Comment (olegshmuelov) [reply operator/node.go]: Applied based on @oleg-ssvlabs suggestion here https://github.com/ssvlabs/ssv/pull/2415#discussion_r2310252359

Comment (iurii-ssv) [reply operator/node.go]: I think it ties into this another tread https://github.com/ssvlabs/ssv/pull/2415#discussion_r2311882485 as well, so I'll close this one to keep it in one place

File: operator/node.go (hunk 62 above)
Comment (iurii-ssv) [reply operator/node.go:115]: This discussion ties into my comment here - https://github.com/ssvlabs/ssv/pull/2415#discussion_r2291471053

> slightly adjusted logging
https://github.com/ssvlabs/ssv/commit/75ec2e98f98b4d44d054f5dfa3f664dcf3379509

while it's good to have this behavior documented ^, I'm thinking maybe we can completely resolve it.

I think the issue stems from the fact that we "connect" `GoClient` in the constructor `goclient.New` rather than delaying that until `GoClient` has everything it needs - `feeRecipientCtrl` in this case. So maybe we could move the "connect" logic out of `goclient.New` and connect explicitly later.

That would still not be the best solution, from what I understand. Here is how we can address it:
- instead of directly spinning off a `go gc.handleProposalPreparationsOnReconnect(ctx, s, logger)` in `OnActive` we could generate an event
- this event will be accepted, buffered, delivered by newly introduced component, call it `CLEventer`, to anybody who is interested in processing it (`recipientController` in our case)
- the `CLEventer` could even hold the event (buffer it) until processors are ready, but in our case we probably can simply drop the reconnect-event if `recipientController` isn't listening to `CLEventer` events yet
- the `CLEventer` needs to be created prior to both `GoClient` and `recipientController`, it will absorb(incapsulate) all the logic of "checking for whether we have ready consumers" (that `if provider == nil` case)

That ^ might seems like an overkill, but our core initialization logic is only getting more complex over time ... I'm kind of afraid we might drown in the complexity eventually if we don't start refactoring it like that soon.

Comment (olegshmuelov) [reply operator/node.go:115]: @iurii-ssv, 

As you noted, the event-driven approach might be more complexity than needed for this particular case.

Regarding moving the "connect" logic out of `goclient.New` - that's an interesting idea that could improve the architecture. 
However, implementing this would require significant refactoring across multiple components, which seems disproportionate for addressing an edge case that only occurs during the first few milliseconds of startup and is already safely handled. The nil check ensures that if there's no provider yet, there are no preparations to re-submit anyway.

Given the above, I think the current approach is the right balance for this PR

Comment (iurii-ssv) [reply operator/node.go:115]: Yeah, that can be done in a separate PR later, just outlined the ideas while we are at it :)
