### PR TITLE
Fix skipped unit tests

### LINKED ISSUE #1552: Fix skipped tests
We're skipping quite a lot of tests currently because they fail. After we're done fixing them we should make sure no test is skipped.

### PR DESCRIPTION
**Pull request by nkryuchkov**
Closes #1552

- fix [TestTopicManager](https://github.com/ssvlabs/ssv/pull/1539/commits/bcb319cb033ef84579bff60a0049e6332bc71e77)
- fix p2p tests
- make integration tests runnable, 
    - however, they don't pass, but since they are broken on `main`, this is out of scope of this PR

### CODE REVIEW

File: network/p2p/p2p_test.go [hunk 1]
```diff
@@ -225,49 +257,86 @@ func TestWaitSubsetOfPeers(t *testing.T) {
...
+			},
+			Liquidated: false,
+		},
+	}
+	committeeID := share.CommitteeID()
+
+	fullData := spectestingutils.TestingQBFTFullData
+
+	encodedCommitteeID := append(bytes.Repeat([]byte{0}, 16), committeeID[:]...)
+	committeeIdentifier := spectypes.NewMsgID(netCfg.DomainType(), encodedCommitteeID, spectypes.RoleCommittee)
```
Comment (y0sher) [inline network/p2p/p2p_test.go:279]: this function only generate committee role message, we should add other single validator runners to this test messages as well. 

task: add validator duties (proposer/synccommitteecontribution/aggregator) to generatemsg or create another function and use in `TestP2pNetwork_SubscribeBroadcast`

File: network/p2p/p2p_validation_test.go [hunk 2]
```diff
@@ -46,28 +49,103 @@ func TestP2pNetwork_MessageValidation(t *testing.T) {
...
-		validators[i] = hex.EncodeToString(validator[:])
-	}
-	var mtx sync.Mutex
+	shares := generateShares(t, validatorCount)
+
 	// Create a MessageValidator to accept/reject/ignore messages according to their role type.
 	const (
 		acceptedRole = spectypes.RoleProposer
 		ignoredRole  = spectypes.RoleAggregator
 		rejectedRole = spectypes.RoleSyncCommitteeContribution
```
Comment (y0sher) [inline network/p2p/p2p_validation_test.go:58]: this tests runs only single validator role messages. we should replace one of the message role to be `RoleCommittee` so we test both types of messages. 

task: Test RoleCommittee messages in `TestP2pNetwork_MessageValidation`

**Review by y0sher — APPROVED** [review]
task: bring back genesis p2p tests and run them on genesisP2P wrapper.

**Review by moshe-blox — APPROVED** [review]
